name: Install Actions Runner System
on: 
  push:
    branches:
      - master
      - main
    tags:        
      - v*
      
jobs:
  deploy-certmanager:
    runs-on: ["cicd-infra", "build.mdw.nicks.world"]
    environment: dev
    steps:
      - name: Install CertManager
        run: |
          helm repo add jetstack https://charts.jetstack.io
          helm repo update
          helm install \
          cert-manager jetstack/cert-manager \
          --namespace cert-manager \
          --create-namespace \
          --version v1.6.0 \
          --set installCRDs=true
